### ISSUE TITLE
Jandi

### ISSUE THREAD

**Issue by c-shankar** [saenzramiro/rambox-services-contrib#10]
### URL

https://www.jandi.com

### LOGO

https://cdn.jandi.com/landing/assets/images/header/5fc1e2d6.jandi-logotype.svg

**Comment by TriiNoxYs** [comment]
Added a PullRequest for that: saenzramiro/rambox#636

**Comment by alexandregv** [comment]
Since Jandi was added by saenzramiro/rambox#636, I think this PR should be closed.
