### ISSUE TITLE
Tawk.to

### ISSUE THREAD

**Issue by YohananDiamond** [saenzramiro/rambox-services-contrib#21]
### URL

https//tawk.to

### LOGO

https://www.tawk.to/wp-content/uploads/2015/04/tawky_big.png

### Unread Code

```javascript
function checkUnread() {
    var e = document.getElementsByClassName("unread_countValue");
    var t = 0;
    for( i = 0; i < e.length; i++ ) t += parseInt(e[i].innerHTML.trim());
    updateBadge(t);
}

function updateBadge(e) {
    e >= 1 ? document.title = "(" + e + ") " + originalTitle : document.title = originalTitle
}
var originalTitle = document.title;
setInterval(checkUnread, 3000);
```

**Comment by sminagil** [comment]
@YohananDiamond Thanks, but I can not seem to get the unread messages to display. Has there been a change?

**Comment by YohananDiamond** [comment]
@sminagil hey, I didn't know if it was going to work, I used the default code in the issue template. Also, sorry for not answering for a long time.

**Comment by YohananDiamond** [comment]
Closed due to inactivity.
