### ISSUE TITLE
Zimbra

### ISSUE THREAD

**Issue by flying-sheep** [saenzramiro/rambox-services-contrib#3]
### URL

https://zimbra.com/
### LOGO

https://xmission.com/blog/wp-content/uploads/2015/12/zimbra-logo-color-square-960px.png
### Unread Code

``` javascript
function check_unread() {
    update_badge(appCtxt.getById(ZmFolder.ID_INBOX).numUnread)
}

const original_title = document.title
function update_badge(count) {
    document.title = count > 0 ? `(${count}) ${original_title}` : original_title
}

setInterval(check_unread, 3000)
```

**Comment by TriiNoxYs** [comment]
Zimbra was added in https://github.com/saenzramiro/rambox/commit/8449781697d9c6bb662c72d88c5b69ced9a60bc7

**Comment by flying-sheep** [comment]
oh, yes. i forgot to close this.
